[tool.poetry]
name = "skybrush-blender-plugin"
version = "0.3.0"
description = "Skybrush related add-ons for Blender"
license = "Proprietary"
authors = ["Gabor Vasarhelyi <vasarhelyi@collmot.com>"]

[[tool.poetry.source]]
name = "collmot"
url = "https://pypi.collmot.com/simple/"

[tool.poetry.dependencies]
python = "^3.7"
natsort = "^7.1.0"
skybrush-studio = { version = "^0.6.0", optional = true }

[tool.poetry.extras]
standalone = ["skybrush-studio"]

[tool.poetry.scripts]
test_matcher = "tests.test_matcher:main"

[tool.poetry.dev-dependencies]
pyclean = "^2.0.0"
pyminifier = "^2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

