[tool.poetry]
name = "skybrush-studio-for-blender"
version = "1.10.1"
description = "Skybrush Studio for Blender is a professional drone show designer framework integrated into Blender"
license = "Proprietary"
authors = ["CollMot Robotics Ltd. <hello@skybrush.io>"]
maintainers = ["Tamas Nepusz <tamas@collmot.com>", "Gabor Vasarhelyi <vasarhelyi@collmot.com>"]
homepage = "https://skybrush.io"
repository = "https://git.collmot.com/skybrush/plugin-blender"
documentation = "https://doc.collmot.com/public/skybrush-plugin-blender/latest/"

[[tool.poetry.source]]
name = "collmot"
url = "https://pypi.collmot.com/simple/"

[tool.poetry.dependencies]
python = "^3.7"
natsort = "^8.0.0"
skybrush-studio = { version = "^2.1.0", optional = true }

[tool.poetry.extras]
standalone = ["skybrush-studio"]

[tool.poetry.scripts]
test_matcher = "tests.test_matcher:main"

[tool.poetry.dev-dependencies]
pyclean = "^2.0.0"
pyminifier = "^2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

